# Basic information about this project
[content]
name = "WildMonsterHunt"
version = "1.0.0"
authors = []
game_version = "4.04"
scripts_root = "src/modWildMonsterHunt"

# Any dependencies that this project might need
[dependencies]
wide-content0 = true

# For details check the manual
# https://spontancombust.github.io/witcherscript-ide/user-manual/project-system/#manifest-format
